### ISSUE TITLE
Use native better-sqlite3 Error

### ISSUE THREAD

**Issue by chenyuyu118** [vite-plugin/vite-plugin-native#3]
I follow the example of serialport.
```js
{
          entry: "electron/worker.ts",
          onstart(option) {
            option.reload()
          },
          vite: {
            build: {
              rollupOptions: {
                external: ['sqlite3', "better-sqlite3"]
              },
            },
            plugins: [
                native({
                  outDir: 'dist-electron',
                })
            ]
          }
        }
```
but error occurs like bellow:
```
node:fs:1396
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir '/Auto-Defect-Detect/defect-detect/D:/Auto-Defect-Detect/defect-detect/dist-electron'
    at Object.mkdirSync (node:fs:1396:3)
    at configResolved (D:\Auto-Defect-Detect\defect-detect\node_modules\.store\vite-plugin-native@0.2.0\node_modules\vite-plugin-native\dist\index.js:143:12)
    at file:///D:/Auto-Defect-Detect/defect-detect/node_modules/.store/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:65946:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///D:/Auto-Defect-Detect/defect-detect/node_modules/.store/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:65946:14)
    at async Module.build (file:///D:/Auto-Defect-Detect/defect-detect/node_modules/.store/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:47852:20) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/Auto-Defect-Detect/defect-detect/D:/Auto-Defect-Detect/defect-detect/dist-electron'
}
```

**Comment by yejimeiming** [comment]
Can you try use a absolute path other than relative path.

**Comment by chenyuyu118** [comment]
> Can you try use a absolute path other than relative path.

I have tried.But the result output path always have a relative project path whatever the outdir i set.😰

**Comment by yejimeiming** [comment]
Okay! I'll try resolve it in the week end :)

**Comment by caoxiemeihao** [comment]
Maybe you can try the following two cased, the way `better-sqlite3` loads `.node` files is not recognized by the  bundler(`Vite`, `Rollup`, `Webpack`) friendly,

https://github.com/caoxiemeihao/electron-vite-samples/tree/main/better-sqlite3-renderer-process
https://github.com/caoxiemeihao/electron-vite-samples/tree/main/better-sqlite3-main-process

**Comment by caoxiemeihao** [comment]
v2.0.0 is out!
